### ISSUE TITLE
Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources

### ISSUE THREAD

**Issue by leehuwuj** [Thelin90/deiteo#6]
Hi.
I still have issue when submit task outside master node.

When I submit an task inside master pod:
`spark-submit --master spark://sparkmaster:7077 --total-executor-cores 1 --executor-memory 512m --class org.apache.spark.examples.SparkPi dags/spark-examples_2.11-2.4.6.jar`
It runs OK.

Assume I'm an Python pod, It has an spark bin can run spark-submit command. Run submit task again, the "Initial job has not accepted any resources" issue still happen.
`spark-submit --master spark://sparkmaster:7077 --total-executor-cores 1 --executor-memory 512m --class org.apache.spark.examples.SparkPi dags/spark-examples_2.11-2.4.6.jar`

Log of worker node look like bellow:
```
20/11/26 08:09:03 INFO Worker: Asked to launch executor app-20201126080903-0000/0 for test.py

20/11/26 08:09:03 INFO SecurityManager: Changing view acls to: root

20/11/26 08:09:03 INFO SecurityManager: Changing modify acls to: root

20/11/26 08:09:03 INFO SecurityManager: Changing view acls groups to:

20/11/26 08:09:03 INFO SecurityManager: Changing modify acls groups to:

20/11/26 08:09:03 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(root); groups with view permissions: Set(); users with modify permissions: Set(root); groups with modify permissions: Set()

20/11/26 08:09:03 INFO ExecutorRunner: Launch command: "/usr/lib/jvm/java-8-openjdk-amd64//bin/java" "-cp" "/usr/local/spark/conf/:/usr/local/spark/jars/*" "-Xmx1024M" "-Dspark.driver.port=41149" "org.apache.spark.executor.CoarseGrainedExecutorBackend" "--driver-url" "spark://CoarseGrainedScheduler@airflow-5cf9bd5c9b-jtr8j:41149" "--executor-id" "0" "--hostname" "10.1.2.169" "--cores" "1" "--app-id" "app-20201126080903-0000" "--worker-url" "spark://Worker@10.1.2.169:42579"
```

Log of master pod:
```
20/11/26 08:09:25 INFO Master: Received unregister request from application app-20201126080903-0000

20/11/26 08:09:25 INFO Master: Removing app app-20201126080903-0000
```

Do you have any solution for it?

**Comment by leehuwuj** [comment]
Log from Python pod:

```
log4j:WARN No appenders could be found for logger (org.apache.hadoop.util.NativeCodeLoader).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/11/26 08:19:29 INFO SecurityManager: Changing view acls to: airflow
20/11/26 08:19:29 INFO SecurityManager: Changing modify acls to: airflow
20/11/26 08:19:29 INFO SecurityManager: Changing view acls groups to:
20/11/26 08:19:29 INFO SecurityManager: Changing modify acls groups to:
20/11/26 08:19:29 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(airflow); groups with view permissions: Set(); users  with modify permissions: Set(airflow); groups with modify permissions: Set()
20/11/26 08:19:30 INFO Utils: Successfully started service 'driverClient' on port 46097.
20/11/26 08:19:30 INFO TransportClientFactory: Successfully created connection to sparkmaster/10.101.195.24:7077 after 38 ms (0 ms spent in bootstraps)
20/11/26 08:19:30 INFO ClientEndpoint: Driver successfully submitted as driver-20201126081930-0000
20/11/26 08:19:30 INFO ClientEndpoint: ... waiting before polling master for driver state
20/11/26 08:19:35 INFO ClientEndpoint: ... polling master for driver state
20/11/26 08:19:35 INFO ClientEndpoint: State of driver-20201126081930-0000 is ERROR
20/11/26 08:19:35 ERROR ClientEndpoint: Exception from cluster was: java.nio.file.NoSuchFileException: /usr/local/airflow/dags/spark-examples_2.11-2.4.6.jar
java.nio.file.NoSuchFileException: /usr/local/airflow/dags/spark-examples_2.11-2.4.6.jar
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
        at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
        at java.nio.file.Files.copy(Files.java:1274)
        at org.apache.spark.util.Utils$.copyRecursive(Utils.scala:690)
        at org.apache.spark.util.Utils$.copyFile(Utils.scala:661)
        at org.apache.spark.util.Utils$.doFetchFile(Utils.scala:735)
        at org.apache.spark.util.Utils$.fetchFile(Utils.scala:535)
        at org.apache.spark.deploy.worker.DriverRunner.downloadUserJar(DriverRunner.scala:166)
        at org.apache.spark.deploy.worker.DriverRunner.prepareAndRunDriver(DriverRunner.scala:177)
        at org.apache.spark.deploy.worker.DriverRunner$$anon$2.run(DriverRunner.scala:96)
20/11/26 08:19:35 INFO ShutdownHookManager: Shutdown hook called
20/11/26 08:19:35 INFO ShutdownHookManager: Deleting directory /tmp/spark-ce1b37ca-ea24-4256-ab0a-e8db480e251c
airflow@airflow-5cf9bd5c9b-jtr8j:~$ spark/bin/spark-submit  --master spark://sparkmaster:7077 --class org.apache.spark.examples.SparkPi dags/spark-examples_2.11-2.4.6.jar
20/11/26 08:19:53 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/11/26 08:19:53 INFO SparkContext: Running Spark version 3.0.1
20/11/26 08:19:53 INFO ResourceUtils: ==============================================================
20/11/26 08:19:53 INFO ResourceUtils: Resources for spark.driver:

20/11/26 08:19:53 INFO ResourceUtils: ==============================================================
20/11/26 08:19:53 INFO SparkContext: Submitted application: Spark Pi
20/11/26 08:19:53 INFO SecurityManager: Changing view acls to: airflow
20/11/26 08:19:53 INFO SecurityManager: Changing modify acls to: airflow
20/11/26 08:19:53 INFO SecurityManager: Changing view acls groups to:
20/11/26 08:19:53 INFO SecurityManager: Changing modify acls groups to:
20/11/26 08:19:53 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(airflow); groups with view permissions: Set(); users  with modify permissions: Set(airflow); groups with modify permissions: Set()
20/11/26 08:19:53 INFO Utils: Successfully started service 'sparkDriver' on port 37501.
20/11/26 08:19:53 INFO SparkEnv: Registering MapOutputTracker
20/11/26 08:19:53 INFO SparkEnv: Registering BlockManagerMaster
20/11/26 08:19:53 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
20/11/26 08:19:53 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
20/11/26 08:19:53 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
20/11/26 08:19:53 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-0eba8afb-b367-43be-a1ad-adf807659b58
20/11/26 08:19:53 INFO MemoryStore: MemoryStore started with capacity 413.9 MiB
20/11/26 08:19:53 INFO SparkEnv: Registering OutputCommitCoordinator
20/11/26 08:19:54 INFO Utils: Successfully started service 'SparkUI' on port 4040.
20/11/26 08:19:54 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://airflow-5cf9bd5c9b-jtr8j:4040
20/11/26 08:19:54 INFO SparkContext: Added JAR file:/usr/local/airflow/dags/spark-examples_2.11-2.4.6.jar at spark://airflow-5cf9bd5c9b-jtr8j:37501/jars/spark-examples_2.11-2.4.6.jar with timestamp 1606378794314
20/11/26 08:19:54 WARN SparkContext: Please ensure that the number of slots available on your executors is limited by the number of cores to task cpus and not another custom resource. If cores is not the limiting resource then dynamic allocation will not work properly!
20/11/26 08:19:54 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://sparkmaster:7077...
20/11/26 08:19:54 INFO TransportClientFactory: Successfully created connection to sparkmaster/10.101.195.24:7077 after 36 ms (0 ms spent in bootstraps)
20/11/26 08:19:54 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20201126081954-0001
20/11/26 08:19:54 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20201126081954-0001/0 on worker-20201126080828-10.1.2.169-42579 (10.1.2.169:42579) with 1 core(s)
20/11/26 08:19:54 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 35731.
20/11/26 08:19:54 INFO NettyBlockTransferService: Server created on airflow-5cf9bd5c9b-jtr8j:35731
20/11/26 08:19:54 INFO StandaloneSchedulerBackend: Granted executor ID app-20201126081954-0001/0 on hostPort 10.1.2.169:42579 with 1 core(s), 1024.0 MiB RAM
20/11/26 08:19:54 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
20/11/26 08:19:54 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20201126081954-0001/1 on worker-20201126080828-10.1.2.170-32979 (10.1.2.170:32979) with 1 core(s)
20/11/26 08:19:54 INFO StandaloneSchedulerBackend: Granted executor ID app-20201126081954-0001/1 on hostPort 10.1.2.170:32979 with 1 core(s), 1024.0 MiB RAM
20/11/26 08:19:54 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, airflow-5cf9bd5c9b-jtr8j, 35731, None)
20/11/26 08:19:54 INFO BlockManagerMasterEndpoint: Registering block manager airflow-5cf9bd5c9b-jtr8j:35731 with 413.9 MiB RAM, BlockManagerId(driver, airflow-5cf9bd5c9b-jtr8j, 35731, None)
20/11/26 08:19:54 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20201126081954-0001/1 is now RUNNING
20/11/26 08:19:54 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20201126081954-0001/0 is now RUNNING
20/11/26 08:19:54 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, airflow-5cf9bd5c9b-jtr8j, 35731, None)
20/11/26 08:19:54 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, airflow-5cf9bd5c9b-jtr8j, 35731, None)
20/11/26 08:19:55 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
20/11/26 08:19:56 INFO SparkContext: Starting job: reduce at SparkPi.scala:38
20/11/26 08:19:56 INFO DAGScheduler: Got job 0 (reduce at SparkPi.scala:38) with 2 output partitions
20/11/26 08:19:56 INFO DAGScheduler: Final stage: ResultStage 0 (reduce at SparkPi.scala:38)
20/11/26 08:19:56 INFO DAGScheduler: Parents of final stage: List()
20/11/26 08:19:56 INFO DAGScheduler: Missing parents: List()
20/11/26 08:19:56 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[1] at map at SparkPi.scala:34), which has no missing parents
20/11/26 08:19:56 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 2.9 KiB, free 413.9 MiB)
20/11/26 08:19:56 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 1691.0 B, free 413.9 MiB)
20/11/26 08:19:56 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on airflow-5cf9bd5c9b-jtr8j:35731 (size: 1691.0 B, free: 413.9 MiB)
20/11/26 08:19:56 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1223
20/11/26 08:19:56 INFO DAGScheduler: Submitting 2 missing tasks from ResultStage 0 (MapPartitionsRDD[1] at map at SparkPi.scala:34) (first 15 tasks are for partitions Vector(0, 1))
20/11/26 08:19:57 INFO TaskSchedulerImpl: Adding task set 0.0 with 2 tasks
20/11/26 08:20:12 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
20/11/26 08:20:27 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
20/11/26 08:20:42 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
```

**Comment by Thelin90** [comment]
Does this happen when you run the code of this repo? @leehuwuj

**Comment by Thelin90** [comment]
I am not sure what you mean with `Python pod`.

Are you saying you are trying to execute spark code from one `k8s` pod to another `k8s` pod? This repo simply supports the setup of the `k8s` cluster with spark, which you then run commands against that `k8s/spark` cluster.

Which I do here: https://github.com/Thelin90/deiteo#verify-k8s-cluster

```bash
kubectl exec <pod> -it -- spark-submit example_spark.py
```

I have added an example app here, which I include when I build spark: https://github.com/Thelin90/deiteo/blob/master/tools/docker/spark/example_spark.py

If you are creating an additional pod, which you seem to do, you need to create a service for that so it can reach the other pod, which I am not supporting here.

It does not look like you are following my `README` instructions, and that you are talking about functionality I do not support in this repo, correct me if I am wrong.

**Comment by leehuwuj** [comment]
@Thelin90 I means client mode of spark-submit. When you run `kubectl exec <pod> -it -- spark-submit example_spark.py` it's cluster mode. Client-mode submit is that you can submit an python or jar file to a spark cluster (master node).
Example, you're on other pods or anywhere that can connect to spark master nod you can submit an spark task by command:
`spark-submit --deploy-mode client --master spark://sparkmaster:7077 example_spark.py`
NOT
`kubectl exec <pod> -it -- spark-submit example_spark.py`

**Comment by Thelin90** [comment]
Sorry I don't follow what you are talking about, what I do is utilising all
available executors via the master node, that's what spark is for. If you
just wanna run only on the master node then you can do that if that's what
you mean.

**Comment by Thelin90** [comment]
I'm closing this issue, I feel you are not following my instructions, and
you are trying to do something unrelated to what I've posted in the repo.

**Comment by Thelin90** [comment]
@leehuwuj I really don't understand what you are trying to say, have you even looked in my `README` and followed the instructions?

What you are saying above is not even accurate. You must run the command against the pod if you are calling it from another pod, you can't run it without the `kubectl exec`. Your command assume you are running commands from within the pod itself.

What I do in this repo is that I build up the spark cluster in k8s, I then make sure that the master node can distribute the work to the given executors in this case by default 2 workers.

I have an example file which I have provided, you can run any given file you want, with the given settings, it will distribute it amongs the workers, see README he which shows the work being distributed via the UI:

https://github.com/Thelin90/deiteo/blob/master/img/detailedsparkui.png

https://github.com/Thelin90/deiteo/blob/master/img/sparkui.png

The deploy mode is predefined in my `repo` to be what you are doing, the scripts utilise this.

What you are talking about has absolutely nothing to do with my repo, and it is not an issue in my opinion.

Feel free to fork this repo and do whatever you want.

I can just simply strictly advice you to go through my README line by line and follow my instructions and if you want to do something else then just implement it yourself.

I think you need to actually look at my implementation, this is not even needed:

```bash
--master spark://sparkmaster:7077 example_spark.py
```

This is taken care of by the scripts and I am setting this when you build the cluster.

https://github.com/Thelin90/deiteo/blob/master/tools/docker/spark/spark-master.sh

```bash
echo "spark.driver.host $(hostname -i)" >> /usr/local/spark/conf/spark-defaults.conf
echo "spark.driver.bindAddress $(hostname -i)" >> /usr/local/spark/conf/spark-defaults.conf
```

Makes sure it can bind it to the workers.

**Comment by Thelin90** [comment]
> @Thelin90 I means client mode of spark-submit. When you run `kubectl exec <pod> -it -- spark-submit example_spark.py` it's cluster mode. Client-mode submit is that you can submit an python or jar file to a spark cluster (master node).
> Example, you're on other pods or anywhere that can connect to spark master nod you can submit an spark task by command:
> `spark-submit --deploy-mode client --master spark://sparkmaster:7077 example_spark.py`
> NOT
> `kubectl exec <pod> -it -- spark-submit example_spark.py`

Also what you are writing here is not correct, if you are trying to run the spark code from another pod you must execute against that pod.

Your command assume you are running it from within the pod itself.
